AHBCFinalProject/Models/RecipeViewModel.cs
using System;
// using System.Reflection;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AHBCFinalProject.Models
{
    public class RecipeViewModel
    {
        public string Id { get; set; }
        public string Title { get; set; }
        public string Image { get; set; }
        public string ImageType { get; set; }
        public int Servings { get; set; }
        public int ReadyInMinutes { get; set; }
        public string License { get; set; }
        public string SourceName { get; set; }
        public string SourceUrl { get; set; }
        public string SpoonacularSourceUrl { get; set; }
        public int AggregateLikes { get; set; }
        public float HealthScore { get; set; }
        public float SpoonacularScore { get; set; }
        public float PricePerServing { get; set; }
        public object[] AnalyzedInstructions { get; set; }
        public bool Cheap { get; set; }
        public string CreditsText { get; set; }
        public object[] Cuisines { get; set; }
        public bool DairyFree { get; set; }
        public object[] Diets { get; set; }
        public string Gaps { get; set; }
        public bool GlutenFree { get; set; }
        public string Instructions { get; set; }
        public bool Ketogenic { get; set; }
        public bool LowFodmap { get; set; }
        public object[] Occasions { get; set; }
        public bool Sustainable { get; set; }
        public bool Vegan { get; set; }
        public bool Vegetarian { get; set; }
        public bool VeryHealthy { get; set; }
        public bool VeryPopular { get; set; }
        public bool Whole30 { get; set; }
        public int WeightWatcherSmartPoints { get; set; }
        public string[] DishTypes { get; set; }
        public Extendedingredient[] ExtendedIngredients { get; set; }
        public Winepairing WinePairing { get; set; }
    }
}

AHBCFinalProject/Models/RecipesViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AHBCFinalProject.Models
{
    public class RecipesViewModel
    {
        public string Title { get; set; }
        public int RecipeId { get; set; }
    }
}

AHBCFinalProject/Controllers/RecipeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AHBCFinalProject.DAL;
using AHBCFinalProject.Models;
using AHBCFinalProject.Services;
using Microsoft.AspNetCore.Mvc;

namespace AHBCFinalProject.Controllers
{
    public class RecipeController : Controller
    {
        private readonly IRecipeByIdService _recipeByIdService;

        public RecipeController(IRecipeByIdService recipeByIdService)
        {
            _recipeByIdService = recipeByIdService;
        }
        
        public async Task<IActionResult> ViewRecipe(string id)
        {
            var viewModel = await _recipeByIdService.GetRecipeVMById(id);

            return View(viewModel);
        }
    }
}

AHBCFinalProject/Views/Recipe/ViewMealPlanResults.cshtml
@model MPsViewModel

@{
    ViewData["Title"] = "ViewMealPlanResults";
}

<div class="container">
    <div class="centered">
    <h1>Results</h1>


    <div>
        <table>
            <thead>
                <tr>
                    <th>Sunday</th>
                    <th>Monday</th>
                    <th>Tuesday</th>
                    <th>Wednesday</th>
                    <th>Thursday</th>
                    <th>Friday</th>
                    <th>Saturday</th>

                </tr>
            </thead>
            <tbody>
                @foreach (var weeklyPlan in Model.MealPlans)
                {
                    <tr>
                        <td>
                            <a asp-controller="Recipe" asp-action="ViewRecipe" asp-route-id="@weeklyPlan.SundayId">@weeklyPlan.SundayName</a>
                        </td>
                        <td>
                            <a asp-controller="Recipe" asp-action="ViewRecipe" asp-route-id="@weeklyPlan.MondayId">@weeklyPlan.MondayName</a>
                        </td>
                        <td>
                            <a asp-controller="Recipe" asp-action="ViewRecipe" asp-route-id="@weeklyPlan.TuesdayId">@weeklyPlan.TuesdayName</a>
                        </td>
                        <td>
                            <a asp-controller="Recipe" asp-action="ViewRecipe" asp-route-id="@weeklyPlan.WednesdayId">@weeklyPlan.WednesdayName</a>
                        </td>
                        <td>
                            <a asp-controller="Recipe" asp-action="ViewRecipe" asp-route-id="@weeklyPlan.ThursdayId">@weeklyPlan.ThursdayName</a>
                        </td>
                        <td>
                            <a asp-controller="Recipe" asp-action="ViewRecipe" asp-route-id="@weeklyPlan.FridayId">@weeklyPlan.FridayName</a>
                        </td>
                        <td>
                            <a asp-controller="Recipe" asp-action="ViewRecipe" asp-route-id="@weeklyPlan.SaturdayId">@weeklyPlan.SaturdayName</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>

    </div>
</div>

AHBCFinalProject/Views/Recipe/ViewRecipe.cshtml
@model RecipeViewModel

@{
    ViewData["Title"] = "ViewRecipe";
}



<div class="container">
      
    <h3>@Model.Title</h3>
    
    <div class="recipe-ingredients">
        <div class="col-auto">
            <h4 class="ingredients-header">Ingredients</h4>
            @*<ul style="list-style: none; margin:0; padding:0">*@
            <ul class="text-left" style="list-style: none">
                @foreach (var ingredient in Model.ExtendedIngredients)
                {
                    <li>@ingredient.Amount @ingredient.Unit @ingredient.OriginalName</li>
                }
            </ul>
            <div class="recipe-img">
                <figure class="figure">
                    <img src="@Model.Image" class="figure-img img-fluid rounded">
                    <figcaption class="figure-caption"></figcaption>
                </figure>
            </div>
        </div>
        <div class="recipe-instructions offset-1">
            <h4>Instructions</h4>
            <p>@Model.Instructions</p>
        </div>
    </div>
    <a class="btn btn-outline-secondary" asp-controller="User" asp-action="AddToFavorites" role="button" asp-route-id="@Model.Id">Add To Favorites<br /></a>

</div>

AHBCFinalProject/Views/Recipe/ViewRecipes.cshtml
@model ListOfRecipesViewModel
@{
    ViewData["Title"] = "ViewRecipes";
}

<h1>View All Recipes</h1>

<div class="container">
    <div class="centered">
        <table class="table table-bordered table table-hover">
            <thead class="card-header-pills">
                <tr>
                    <th class="font-weight-bold" id="LoR_header">List of Recipes</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var recipe in Model.ListOfRecipes)
                {
                    <tr>
                        <td>
                            <a asp-controller="Recipe" asp-action="ViewRecipe" class="text-secondary" asp-route-id="@recipe.Id">@recipe.Title</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
</div>
</div>